(library
 (name runner)
 (public_name spectec.runner)
 (modules
  runner
  checkpoint
  json_mutator
  source_selector
  testgen
  testgen_data
  uid_parser)
 (libraries
  core
  unix
  spectec
  spectec.batch
  spectec.common
  spectec.lang
  spectec.pass
  spectec.interp
  spectec.interface
  spectec.instrumentation
  yojson
  str)
 (preprocess
  (pps ppx_let)))
