(lang dune 3.7)

(name ssz)

(version 0.1.0)

(generate_opam_files true)

(license Apache-2.0)

(maintainers "Jun Song <syjn99@gmail.com>")

(package
 (name ssz)
 (synopsis "SSZ hash_tree_root (merkleization) for OCaml")
 (description
  "Computes SSZ hash_tree_root from a type descriptor and a value, \
   following the SSZ specification, including EIP-7916 progressive lists, \
   EIP-7495 progressive containers and EIP-8016 compatible unions. \
   Serialization is out of scope. The ssz.schema sub-library loads type \
   descriptors and values from JSON.")
 (depends
  (ocaml (>= 4.14))
  digestif
  yojson))
