(* hash_tree_root builtins over the ssz library.

   The fork and preset come from the command line (see [configure]); each selects
   a schema generated by spec/ssz/generate.py and embedded at build time.
   [to_ssz] is the one place that knows how SpecTec values are shaped. *)

open Common.Source
open Lang.Il
open Lang.Xl
open Value
open Builtins
open Error

let ( let* ) = Result.bind

(* Fork and preset *)

let schemas =
  [
    (("capella", "minimal"), Ssz_schemas.capella_minimal);
    (("capella", "mainnet"), Ssz_schemas.capella_mainnet);
    (("deneb", "minimal"), Ssz_schemas.deneb_minimal);
    (("deneb", "mainnet"), Ssz_schemas.deneb_mainnet);
  ]

let schema : Ssz_schema.t option ref = ref None

let configure ~fork ~preset =
  match List.assoc_opt (fork, preset) schemas with
  | None ->
      Error
        (Printf.sprintf "no SSZ schema for fork %S, preset %S (have: %s)" fork
           preset
           (String.concat ", "
              (List.map (fun ((f, p), _) -> f ^ "/" ^ p) schemas)))
  | Some json -> (
      match Ssz_schema.of_json (Yojson.Safe.from_string json) with
      | Ok s ->
          schema := Some s;
          Ok ()
      | Error e -> Error (Printf.sprintf "SSZ schema %s/%s: %s" fork preset e))

let current ~at =
  match !schema with
  | Some s -> Ok s
  | None -> Error (runtime at "SSZ schema not selected: pass --fork")

(* A type named in the schema, or the type of a container's field. *)
let lookup ~at ?field name =
  let* s = current ~at in
  match (Ssz_schema.find s name, field) with
  | None, _ -> Error (runtime at ("SSZ schema has no type " ^ name))
  | Some t, None -> Ok t
  | Some (Ssz.Container fields), Some f -> (
      match List.assoc_opt f fields with
      | Some t -> Ok t
      | None -> Error (runtime at (Printf.sprintf "%s has no field %s" name f)))
  | Some _, Some f ->
      Error (runtime at (Printf.sprintf "%s.%s: not a container" name f))

(* SpecTec values *)

exception Shape of string

let shape fmt = Printf.ksprintf (fun m -> raise (Shape m)) fmt

(* Little-endian bytes of a non-negative integer, exactly [size] wide. *)
let le_bytes ~size (n : Bigint.t) =
  if Bigint.(n < zero) then shape "negative value %s" (Bigint.to_string n);
  let bits = Z.to_bits (Bigint.to_zarith_bigint n) in
  let len = String.length bits in
  if
    len > size
    && String.exists (( <> ) '\000') (String.sub bits size (len - size))
  then shape "%s does not fit in %d bytes" (Bigint.to_string n) size;
  if len >= size then String.sub bits 0 size
  else bits ^ String.make (size - len) '\000'

(* A byte string stored as a big-endian integer. *)
let be_bytes ~size n =
  let le = le_bytes ~size n in
  String.init size (fun i -> le.[size - 1 - i])

let num (v : Value.t) =
  match v.it with
  | NumV n -> Num.to_int n
  | BytesV { num; _ } -> num
  | _ -> shape "expected a number"

(* The ways a SpecTec value can spell a sequence. *)
let elements (v : Value.t) =
  match v.it with ListV vs | TupleV vs -> vs | _ -> shape "expected a list"

let rec to_ssz (t : Ssz.typ) (v : Value.t) : Ssz.value =
  match (t, v.it) with
  | Uint size, _ -> Uint (le_bytes ~size (num v))
  | Boolean, BoolV b -> Bool b
  | Boolean, _ -> shape "expected a boolean"
  (* Byte strings: a big-endian integer, sized by the type or by BytesV, or bytes one by one. *)
  | ( (Vector (Uint 1, _) | List (Uint 1, _) | Progressive_list (Uint 1)),
      BytesV { num; len } ) ->
      Bytes (be_bytes ~size:len num)
  | Vector (Uint 1, n), NumV x -> Bytes (be_bytes ~size:n (Num.to_int x))
  | (Vector (elem, _) | List (elem, _) | Progressive_list elem), _ ->
      Seq (List.map (to_ssz elem) (elements v))
  | (Bitvector _ | Bitlist _ | Progressive_bitlist), _ ->
      Bits
        (List.map
           (fun (b : Value.t) ->
             match b.it with
             | BoolV b -> b
             | _ -> shape "expected bits as booleans")
           (elements v))
  | (Container fields | Progressive_container { fields; _ }), StructV vfields ->
      let find name =
        match
          List.find_opt
            (fun (atom, _) ->
              String.uppercase_ascii (Atom.to_string atom.it)
              = String.uppercase_ascii name)
            vfields
        with
        | Some (_, fv) -> fv
        | None -> shape "missing field %s" name
      in
      Fields
        (List.map
           (fun (name, ft) ->
             try to_ssz ft (find name) with Shape m -> shape "%s: %s" name m)
           fields)
  | ( (Container fields | Progressive_container { fields; _ }),
      (TupleV vs | ListV vs) ) ->
      if List.length vs <> List.length fields then
        shape "container of %d fields given %d values" (List.length fields)
          (List.length vs);
      Fields (List.map2 (fun (_, ft) fv -> to_ssz ft fv) fields vs)
  | Container _, _ | Progressive_container _, _ -> shape "expected a container"
  | Compatible_union _, _ ->
      shape "compatible unions have no SpecTec encoding yet"

let root_value (r : string) =
  make_bytes
    ~num:
      (Z.of_bits (String.init 32 (fun i -> r.[31 - i]))
      |> Bigint.of_zarith_bigint)
    ~len:32

let root ~at t v =
  match to_ssz t v with
  | exception Shape m -> Error (runtime at ("hash_tree_root: " ^ m))
  | sv -> (
      match Ssz.hash_tree_root t sv with
      | Ok r -> Ok r
      | Error m -> Error (runtime at ("hash_tree_root: " ^ m)))

(* Builtins *)

let hash_tree_root ~name ?field () ~at (v : Value.t) =
  let* t = lookup ~at ?field name in
  let* r = root ~at t v in
  Ok (root_value r)

(* compute_signing_root(object, domain) = hash_tree_root(SigningData(root(object), domain)) *)
let compute_signing_root ~typ () ~at (obj : Value.t) (domain : Value.t) =
  let* t = typ ~at in
  let* signing_data = lookup ~at "SigningData" in
  let* obj_root = root ~at t obj in
  let* domain = root ~at (Ssz.Vector (Uint 1, 32)) domain in
  let* r =
    Result.map_error (runtime at)
      (Ssz.hash_tree_root signing_data
         (Fields [ Bytes obj_root; Bytes domain ]))
  in
  Ok (root_value r)

let builtins : (string * Define.t) list =
  let htr builtin ?field name =
    (builtin, Define.T0.a1 Arg.value (hash_tree_root ~name ?field ()))
  in
  let signing builtin typ =
    (builtin, Define.T0.a2 Arg.value Arg.value (compute_signing_root ~typ ()))
  in
  let named name ~at = lookup ~at name and plain (t : Ssz.typ) ~at:_ = Ok t in
  [
    htr "hash_tree_root_beaconBlockHeader" "BeaconBlockHeader";
    htr "hash_tree_root_beaconBlockBody" "BeaconBlockBody";
    htr "hash_tree_root_depositData" "DepositData";
    htr "hash_tree_root_forkdata" "ForkData";
    htr "hash_tree_root_beaconState" "BeaconState";
    htr "hash_tree_root_beaconBlock" "BeaconBlock";
    htr "hash_tree_root_withdrawals" "ExecutionPayload" ~field:"withdrawals";
    htr "hash_tree_root_roots" "BeaconState" ~field:"block_roots";
    htr "hash_tree_root_tx" "ExecutionPayload" ~field:"transactions";
    signing "compute_signing_root_epoch" (plain (Ssz.Uint 8));
    signing "compute_signing_root_voluntary_exit" (named "VoluntaryExit");
    signing "compute_signing_root_bls_to_execution_change"
      (named "BLSToExecutionChange");
    signing "compute_signing_root_beaconBlockHeader" (named "BeaconBlockHeader");
    signing "compute_signing_root_attestationData" (named "AttestationData");
    signing "compute_signing_root_depositMessage" (named "DepositMessage");
    signing "compute_signing_root_block_root" (plain (Ssz.Vector (Uint 1, 32)));
    signing "compute_signing_root_beaconBlock" (named "BeaconBlock");
  ]
